import { createSlice, createAsyncThunk, type PayloadAction } from '@reduxjs/toolkit';
import api from '../../api/axios';
import type { TaskItem } from '../../types';

interface TasksState {
  items: TaskItem[];
  status: 'idle' | 'loading' | 'succeeded' | 'failed';
  error: string | null;
}

const initialState: TasksState = {
  items: [],
  status: 'idle',
  error: null,
};

export const fetchTasks = createAsyncThunk('tasks/fetchTasks', async (userId: number) => {
  // Pass the userId as a query string parameter
  const response = await api.get<TaskItem[]>(`/Tasks?userId=${userId}`);
  return response.data;
});

// We create a partial type for adding because ID is generated by server
export const addTask = createAsyncThunk('tasks/addTask', async (newTask: Partial<TaskItem>) => {
  const response = await api.post<TaskItem>('/Tasks', newTask);
  return response.data;
});

export const deleteTask = createAsyncThunk('tasks/deleteTask', async (taskId: number) => {
  await api.delete(`/Tasks/${taskId}`);
  return taskId;
});

export const toggleTaskStatus = createAsyncThunk('tasks/toggleStatus', async (task: TaskItem) => {
  const updatedTask = { ...task, isCompleted: !task.isCompleted };
  await api.put(`/Tasks/${task.id}`, updatedTask);
  return updatedTask;
});

export const updateTaskDetails = createAsyncThunk('tasks/updateDetails', async (task: TaskItem) => {
  await api.put(`/Tasks/${task.id}`, task);
  return task;
});

const taskSlice = createSlice({
  name: 'tasks',
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder
      .addCase(fetchTasks.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchTasks.fulfilled, (state, action: PayloadAction<TaskItem[]>) => {
        state.status = 'succeeded';
        state.items = action.payload;
      })
      .addCase(fetchTasks.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.error.message || 'Failed to fetch';
      })
      .addCase(addTask.fulfilled, (state, action: PayloadAction<TaskItem>) => {
        state.items.push(action.payload);
      })
      .addCase(deleteTask.fulfilled, (state, action) => {
        state.items = state.items.filter((task) => task.id !== action.payload);
      })
      .addCase(toggleTaskStatus.fulfilled, (state, action) => {
        const index = state.items.findIndex((t) => t.id === action.payload.id);
        if (index !== -1) {
          state.items[index] = action.payload;
        }
      })
      .addCase(updateTaskDetails.fulfilled, (state, action) => {
        const index = state.items.findIndex((t) => t.id === action.payload.id);
        if (index !== -1) {
          state.items[index] = action.payload;
        }
      });
  },
});

export default taskSlice.reducer;
